<?php
namespace App\Form\Type;

use App\Entity\GuestBookEntity;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GuestBookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('username', TextType::class, ['empty_data' => '']);
        $builder->add('subtitle', TextType::class, ['empty_data' => '']);
        $builder->add('body', TextType::class, ['empty_data' => '']);
        $builder->add('username', EmailType::class, ['required' => false]);
        $builder->add('submit', SubmitType::class);

        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => GuestBookEntity::class
        ]);
        //parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
}